name: lighthouse

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lighthouse CI
        run: npx lhci autorun
